### ISSUE TITLE
Cannot laod chunks correctly in a server save in 1.21

### ISSUE THREAD

**Issue by LecAfyc** [CesiumMC/cesium-fabric#15] opened 2024-08-28 09:25 UTC
Cannot laod chunks correctly in a server save in 1.21.
It can only load a few entities.
And the game crash when player die.

log: [latest.log](https://github.com/user-attachments/files/16781193/latest.log)

**Comment by yamayaki1** [comment] 2024-08-28 10:00
Hello there,

From the `latest.log` you attached it seems that the database that holds all chunk data is corrupt. This should not happen under normal circumstances.

I need some more information about your environment as I have never seen this issue before. 

According to the issue's title you have (probably successfully) run this world on a server. How did you copy this world from the server to your computer? Did you shut down the server before you transferred the world?

Thank you for your help.

**Comment by yamayaki1** [comment] 2024-10-08 15:53
Closing this issue due to inactivity. I can't reproduce the corruption on my end. I suspect hardware failure and/ or copying the database file while there still was data written.

**Closed as not planned by yamayaki1** 2024-10-08 15:53 UTC
Labels: P-High, T-Crash, R-Invalid
